# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created: Sun Dec 15 22:10:03 2013
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1167, 653)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(440, 10, 721, 321))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayoutWidget = QtGui.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 19, 701, 291))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.chartGrid = QtGui.QGridLayout(self.gridLayoutWidget)
        self.chartGrid.setMargin(0)
        self.chartGrid.setObjectName(_fromUtf8("chartGrid"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 311, 91))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.cB_updateInterval = QtGui.QComboBox(self.groupBox_2)
        self.cB_updateInterval.setGeometry(QtCore.QRect(10, 50, 91, 22))
        self.cB_updateInterval.setEditable(False)
        self.cB_updateInterval.setObjectName(_fromUtf8("cB_updateInterval"))
        self.cB_updateInterval.addItem(_fromUtf8(""))
        self.cB_updateInterval.addItem(_fromUtf8(""))
        self.cB_updateInterval.addItem(_fromUtf8(""))
        self.cB_updateInterval.addItem(_fromUtf8(""))
        self.cB_updateInterval.addItem(_fromUtf8(""))
        self.label_btc_2 = QtGui.QLabel(self.groupBox_2)
        self.label_btc_2.setGeometry(QtCore.QRect(110, 50, 31, 21))
        self.label_btc_2.setObjectName(_fromUtf8("label_btc_2"))
        self.label_btc_3 = QtGui.QLabel(self.groupBox_2)
        self.label_btc_3.setGeometry(QtCore.QRect(10, 30, 91, 21))
        self.label_btc_3.setObjectName(_fromUtf8("label_btc_3"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(330, 10, 101, 141))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_btc = QtGui.QLabel(self.groupBox_3)
        self.label_btc.setGeometry(QtCore.QRect(10, 20, 31, 21))
        self.label_btc.setObjectName(_fromUtf8("label_btc"))
        self.label_ltc = QtGui.QLabel(self.groupBox_3)
        self.label_ltc.setGeometry(QtCore.QRect(10, 50, 31, 21))
        self.label_ltc.setObjectName(_fromUtf8("label_ltc"))
        self.label_eur = QtGui.QLabel(self.groupBox_3)
        self.label_eur.setGeometry(QtCore.QRect(10, 110, 31, 21))
        self.label_eur.setObjectName(_fromUtf8("label_eur"))
        self.fund_ltc = QtGui.QLabel(self.groupBox_3)
        self.fund_ltc.setGeometry(QtCore.QRect(40, 50, 31, 21))
        self.fund_ltc.setText(_fromUtf8(""))
        self.fund_ltc.setObjectName(_fromUtf8("fund_ltc"))
        self.fund_btc = QtGui.QLabel(self.groupBox_3)
        self.fund_btc.setGeometry(QtCore.QRect(40, 20, 31, 21))
        self.fund_btc.setText(_fromUtf8(""))
        self.fund_btc.setObjectName(_fromUtf8("fund_btc"))
        self.label_usd = QtGui.QLabel(self.groupBox_3)
        self.label_usd.setGeometry(QtCore.QRect(10, 80, 31, 21))
        self.label_usd.setObjectName(_fromUtf8("label_usd"))
        self.fund_eur = QtGui.QLabel(self.groupBox_3)
        self.fund_eur.setGeometry(QtCore.QRect(40, 110, 31, 21))
        self.fund_eur.setText(_fromUtf8(""))
        self.fund_eur.setObjectName(_fromUtf8("fund_eur"))
        self.fund_usd = QtGui.QLabel(self.groupBox_3)
        self.fund_usd.setGeometry(QtCore.QRect(40, 80, 31, 21))
        self.fund_usd.setText(_fromUtf8(""))
        self.fund_usd.setObjectName(_fromUtf8("fund_usd"))
        self.label_status = QtGui.QLabel(self.centralwidget)
        self.label_status.setGeometry(QtCore.QRect(1070, 580, 91, 21))
        self.label_status.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_status.setAutoFillBackground(False)
        self.label_status.setStyleSheet(_fromUtf8("background-color :red; color : black;border: 1px dotted black"))
        self.label_status.setIndent(6)
        self.label_status.setOpenExternalLinks(False)
        self.label_status.setObjectName(_fromUtf8("label_status"))
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(440, 340, 721, 121))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.groupBox_4)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(9, 19, 701, 91))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.indikatorGrid = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.indikatorGrid.setMargin(0)
        self.indikatorGrid.setObjectName(_fromUtf8("indikatorGrid"))
        self.groupBox_5 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 390, 421, 211))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.logTable = QtGui.QTableWidget(self.groupBox_5)
        self.logTable.setGeometry(QtCore.QRect(10, 20, 401, 181))
        self.logTable.setShowGrid(True)
        self.logTable.setRowCount(0)
        self.logTable.setColumnCount(0)
        self.logTable.setObjectName(_fromUtf8("logTable"))
        self.logTable.horizontalHeader().setCascadingSectionResizes(False)
        self.logTable.verticalHeader().setStretchLastSection(False)
        self.groupBox_6 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 110, 311, 161))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.dSBAmountLTC = QtGui.QDoubleSpinBox(self.groupBox_6)
        self.dSBAmountLTC.setGeometry(QtCore.QRect(10, 50, 81, 22))
        self.dSBAmountLTC.setObjectName(_fromUtf8("dSBAmountLTC"))
        self.dSBFee = QtGui.QDoubleSpinBox(self.groupBox_6)
        self.dSBFee.setGeometry(QtCore.QRect(150, 50, 62, 22))
        self.dSBFee.setObjectName(_fromUtf8("dSBFee"))
        self.label = QtGui.QLabel(self.groupBox_6)
        self.label.setGeometry(QtCore.QRect(150, 30, 71, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox_6)
        self.label_2.setGeometry(QtCore.QRect(220, 40, 21, 41))
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_6)
        self.label_3.setGeometry(QtCore.QRect(100, 50, 56, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox_6)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 91, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.cBMax = QtGui.QCheckBox(self.groupBox_6)
        self.cBMax.setGeometry(QtCore.QRect(10, 80, 51, 18))
        self.cBMax.setObjectName(_fromUtf8("cBMax"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1167, 18))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMen = QtGui.QMenu(self.menubar)
        self.menuMen.setObjectName(_fromUtf8("menuMen"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionConnect = QtGui.QAction(MainWindow)
        self.actionConnect.setObjectName(_fromUtf8("actionConnect"))
        self.actionBeenden = QtGui.QAction(MainWindow)
        self.actionBeenden.setObjectName(_fromUtf8("actionBeenden"))
        self.menuMen.addAction(self.actionConnect)
        self.menuMen.addSeparator()
        self.menuMen.addAction(self.actionBeenden)
        self.menubar.addAction(self.menuMen.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "BTC_autoTrade", None))
        self.groupBox.setTitle(_translate("MainWindow", "Chart", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "General Preferences", None))
        self.cB_updateInterval.setItemText(0, _translate("MainWindow", "2", None))
        self.cB_updateInterval.setItemText(1, _translate("MainWindow", "5", None))
        self.cB_updateInterval.setItemText(2, _translate("MainWindow", "10", None))
        self.cB_updateInterval.setItemText(3, _translate("MainWindow", "15", None))
        self.cB_updateInterval.setItemText(4, _translate("MainWindow", "30", None))
        self.label_btc_2.setText(_translate("MainWindow", "sec", None))
        self.label_btc_3.setText(_translate("MainWindow", "Update interval", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Funds", None))
        self.label_btc.setText(_translate("MainWindow", "BTC", None))
        self.label_ltc.setText(_translate("MainWindow", "LTC", None))
        self.label_eur.setText(_translate("MainWindow", "EUR", None))
        self.label_usd.setText(_translate("MainWindow", "USD", None))
        self.label_status.setText(_translate("MainWindow", "Disconnected", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Indikator", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Log", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Handel Einstellungen", None))
        self.label.setText(_translate("MainWindow", "Gebühren", None))
        self.label_2.setText(_translate("MainWindow", "%", None))
        self.label_3.setText(_translate("MainWindow", "LTC", None))
        self.label_4.setText(_translate("MainWindow", "Handelsmenge", None))
        self.cBMax.setText(_translate("MainWindow", "Max", None))
        self.menuMen.setTitle(_translate("MainWindow", "Menü", None))
        self.actionConnect.setText(_translate("MainWindow", "Connect", None))
        self.actionBeenden.setText(_translate("MainWindow", "Beenden", None))

